### ISSUE TITLE
Unknown error breaks map-get

### ISSUE THREAD

**Issue by josephspens** [lunelson/sass-list-maps#13]
I know the title isn't descriptive to the problems, but I can't find any error output to give more information. I don't know when the problem started, but I've been noticing that simple map-get calls have been failing. Below I have a list, and loop through the list to output some classes.

```sass
$icons: (
	work "\e600",
	people "\e601",
	speech "\e632"
);

@each $icon in $icons {
	$name: key($icon);
	.icon-#{$name} {
		@include icon-font;
		&::before {
			@include icon-font;
			display: inline-block;
			content: map-get($icons, $name);
			vertical-align: text-bottom;
		}
	}
}
```

Strangely only `.icon-speech` has a content property declaration. I've noticed this happening on other nested and multi property lists.

I checked out your [demo area](http://sassmeister.com/gist/4787415116ed1adbc8d9) and when I make any edit (like hit enter after a semicolon) the compiler breaks. I was hoping to paste in my maps and see if I had a syntax error, but I didn't get that far.

Any guidance on how to find more information to debug would be appreciated.

**Comment by lunelson** [comment]
Hi, I'm going to to say it's probably because you've updated libsass? The sassmeister demo no longer works because libsass at sassmeister is at version 3.1 now. Since version 3.0, the native maps functions and syntax are supported in libsass so the functions of this library are conflicting with them. I suggest you adopt the native syntax and you can use my [sass-maps-plus](lunelson/sass-maps-plus) library instead, which provides the same functions but for native maps. 

I'll have to update the readme here on Monday, I've had two issues today due to this :)

**Comment by josephspens** [comment]
Wow, you're right. I reformatted the list into a map, used 3.3 syntax, removed sass-list-maps and everything works. :boom:

Bower must have fetched an updated version of node-sass without me realizing.
