### ISSUE TITLE
Nested maps with 2 keys not looping correctly

### ISSUE THREAD

**Issue by nikglavin** [lunelson/sass-list-maps#14]
Using version 1.0.0-b the following example will not compile if using the output of $lottery as it will return

us-powerball, mega-millions

rather than

us-powerball
mega-millions

works on sassmeister presume they are using v1 adding a third key and will preform the nested loop as expected

````
$variant: 'us';

$_lotteries: (
	us (us-powerball, mega-millions)
);

@each $variant in $_lotteries {
  $variant-lotteries: map-get-z($lotteries, #{map-keys($variant)});
   // It will not loop over each lottery for the us variant
  @each $lottery in $variant-lotteries {
     .test {
        lottery: $lottery;
     } 
  }
}
````

**Comment by lunelson** [comment]
It's hard to tell exactly what you are trying to do here, with setting `$variant: 'us'` before the loop and also using `map-keys($variant)` inside the `map-get-z` function;

however [this is what I get at Sassmeister with your code](http://sassmeister.com/gist/42721e5cddcc13d1f386), and in any case I recommend you move to using native maps rather than 'list-maps', which just a polyfill I created when libsass did not yet support native maps. The newer version of this function library is [sass-maps-plus](https://github.com/lunelson/sass-maps-plus), which has the same functions working the same way, but with native syntax. Native syntax is faster, more stable, and I think will express your use case here more clearly
